# Databricks notebook source
# MAGIC %md
# MAGIC # Task 4: Lever Loop — Training Guide
# MAGIC
# MAGIC | Quick Reference | |
# MAGIC |---|---|
# MAGIC | **Task** | 4 of 6 — Lever Loop (Adaptive Optimization Engine) |
# MAGIC | **Harness functions** | `_run_lever_loop()` in `optimization/harness.py` |
# MAGIC | **Reads from** | `preflight` (run context, levers, max_iterations) + `baseline_eval` (scores, thresholds_met, model_id) + `enrichment` (enrichment_model_id, enrichment_skipped) |
# MAGIC | **Publishes to** | `finalize` (scores, accuracy, model_id, iteration_counter, debug_info) |
# MAGIC | **Typical duration** | 15–90 min (depends on iteration count and benchmark size) |
# MAGIC | **Log label** | `[TASK-4 LEVER_LOOP]` |
# MAGIC
# MAGIC ## 🎯 Purpose
# MAGIC
# MAGIC Task 4 is the **adaptive optimization engine** of the Genie Space Optimizer. Proactive enrichment has already been applied by Task 3. Each iteration it re-diagnoses failures from the latest evaluation, re-strategizes by generating a single targeted action group, applies patches through a 3-gate pattern, and reflects on the outcome to guide the next iteration.
# MAGIC
# MAGIC ## 🏗️ DAG Position
# MAGIC
# MAGIC | Step | Task | Status | Reads From | Publishes To |
# MAGIC |:----:|------|:------:|------------|--------------|
# MAGIC | 1 | preflight | Done | widgets | all tasks |
# MAGIC | 2 | baseline_eval | Done | preflight | enrichment |
# MAGIC | 3 | enrichment | Done | preflight + baseline | lever_loop |
# MAGIC | 4 | **lever_loop** | **⬅️ THIS TASK** | preflight + baseline + enrichment | finalize |
# MAGIC | 5 | finalize | Next | lever_loop | deploy |
# MAGIC | 6 | deploy | Pending | preflight + finalize | *(terminal)* |
# MAGIC
# MAGIC > **📝 Note:** This task runs only when baseline does *not* meet thresholds (`run_if: !thresholds_met`). An internal baseline gate provides a safety check even if the job configuration allows the task to run.
# MAGIC
# MAGIC ## The 5 Lever Categories
# MAGIC
# MAGIC Patches generated by the adaptive strategist draw from 5 lever categories. The strategist decides which levers to use per iteration based on the current failure landscape — they are **not** iterated sequentially.
# MAGIC
# MAGIC | Lever | Name | What It Optimizes | Example Patches | Risk |
# MAGIC |:-----:|------|-------------------|-----------------|:----:|
# MAGIC | 1 | **Tables & Columns** | Column descriptions, aliases, synonyms | `update_column_description`, `add_column_synonym` | 🔵 Low–Med |
# MAGIC | 2 | **Metric Views** | MV measures, dimensions, YAML definitions | `update_mv_measure`, `add_mv_dimension`, `update_mv_yaml` | 🟠 Med–High |
# MAGIC | 3 | **Table-Valued Functions** | TVF SQL, parameters, signatures | `update_tvf_sql`, `add_tvf_parameter`, `add_tvf` | 🟠 Med–High |
# MAGIC | 4 | **Join Specifications** | Table relationships, join columns (reactive + column-name discovery) | `add_join_spec`, `update_join_spec`, `remove_join_spec` | 🔵 Medium |
# MAGIC | 5 | **Genie Space Instructions** | Routing rules, disambiguation, default behaviors, example SQL queries | `add_example_sql`, `update_example_sql`, `add_instruction`, `update_instruction` | 🔵 Low–Med |
# MAGIC
# MAGIC > **📝 Note:** Lever 5 priority hierarchy: SQL expressions > example SQL > text instructions. Most Lever 5 failures are routed to `add_example_sql` (preferred), with text instructions used only as a last resort. A **100-instruction slot budget** is enforced (see Instruction Slot Budget section below).
# MAGIC
# MAGIC > **📝 Note:** Format assistance and entity matching are applied automatically between baseline and the lever loop (Stage 2.5). Levers 1–3 are governed by `apply_mode` (genie_config, uc_artifact, or both). Levers 4–5 always write to Genie Space config.
# MAGIC
# MAGIC ## Convergence Logic
# MAGIC
# MAGIC The adaptive loop exits when any of these conditions is met:
# MAGIC - **All thresholds met** — every judge (e.g. syntax_validity, schema_accuracy) meets its target
# MAGIC - **Diminishing returns** — the last N accepted iterations each improved accuracy by less than epsilon (default 2.0%)
# MAGIC - **No actionable clusters** — no remaining failure clusters to address (all fixed or all previously attempted)
# MAGIC - **Strategist produces 0 action groups** — the LLM determines there is nothing left to fix
# MAGIC - **Max iterations reached** — `iteration_counter >= max_iterations`

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🔧 Architecture: Adaptive Iteration Cycle
# MAGIC
# MAGIC The lever loop uses an **adaptive iteration cycle**. Each iteration re-diagnoses, re-strategizes, applies, evaluates, and reflects:
# MAGIC
# MAGIC ```
# MAGIC for iteration in 1..max_iterations:
# MAGIC     re-cluster failures → score by impact → strategist (1 AG) →
# MAGIC     apply patches → 3-gate eval → accept/rollback → reflect
# MAGIC ```
# MAGIC
# MAGIC | Step | What Happens | Key Function |
# MAGIC |:----:|--------------|-------------|
# MAGIC | 1 | **Re-cluster** failures from latest eval (baseline on iter 1, gate-3 results on iter 2+) | `_analyze_and_distribute()` |
# MAGIC | 2 | **Filter** clusters already attempted via `tried_patches` | `_filter_tried_clusters()` |
# MAGIC | 3 | **Rank** clusters by impact score (causal weight, severity, fixability) | `rank_clusters()` |
# MAGIC | 4 | **Strategist** call: 1 LLM call with reflection buffer and priority ranking produces exactly 1 action group | `_call_llm_for_adaptive_strategy()` |
# MAGIC | 5 | **Generate** proposals and **apply** patches | `generate_proposals_from_strategy()` + `apply_patch_set()` |
# MAGIC | 6 | **3-gate eval**: slice → P0 → full | `_run_gate_checks()` |
# MAGIC | 7 | **Accept or rollback** based on gate results | `rollback()` on failure |
# MAGIC | 8 | **Reflect**: build reflection entry, update `tried_patches` | `_build_reflection_entry()` |
# MAGIC
# MAGIC ### 3-Gate Pattern
# MAGIC
# MAGIC For each iteration, after patches are applied, the harness runs **three evaluation gates** in sequence:
# MAGIC
# MAGIC | Gate | Scope | Pass Condition | On Failure |
# MAGIC |:----:|-------|---------------|------------|
# MAGIC | **1. Slice** | Only benchmarks touching **patched objects** | No regression vs. best scores (noise-floor-adjusted `SLICE_GATE_TOLERANCE`) | Rollback → reflect → next iteration |
# MAGIC | **2. P0** | Top 3 most critical questions | Zero P0 failures | Rollback → reflect → next iteration |
# MAGIC | **3. Full** | All benchmarks | No regression vs. best scores (noise-floor-adjusted `REGRESSION_THRESHOLD`) | Rollback → reflect → next iteration |
# MAGIC
# MAGIC **On full-gate success:** Accept iteration → update best_scores/best_model_id → write iteration to Delta → register instruction version snapshot → update reference SQLs → log expectations on traces.
# MAGIC
# MAGIC ### Reflection Buffer
# MAGIC
# MAGIC Each iteration produces a **reflection entry** recording what was attempted, whether it was accepted or rolled back, the score delta, which levers and targets were involved, and lessons learned. The strategist receives recent reflections in full detail and older ones in compressed form. A **"DO NOT RETRY" list** prevents the strategist from repeating previously failed approaches.
# MAGIC
# MAGIC ### Cluster-Level Impact Scoring
# MAGIC
# MAGIC Failure clusters are scored deterministically using: question count in the cluster, causal weight of the judges that flagged it, failure type severity, and fixability (whether a counterfactual SQL exists). Higher-impact clusters are addressed first.
# MAGIC
# MAGIC ### Rollback Mechanism
# MAGIC
# MAGIC When any gate fails, `rollback(apply_log, w, space_id, metadata_snapshot)` reverses all applied patches. The space returns to its pre-iteration state. Patches are marked as rolled back in Delta for audit.
# MAGIC
# MAGIC ### Instruction Slot Budget
# MAGIC
# MAGIC The Genie API enforces a hard limit of **100 instruction slots** (each example SQL = 1, each SQL function = 1, the entire text instructions block = 1). The optimizer enforces this at three levels:
# MAGIC - **Proposal validation**: `_validate_lever5_proposals()` caps `add_example_sql` proposals at remaining budget
# MAGIC - **Post-apply guard**: `apply_patch_set()` trims excess examples if the limit is somehow breached
# MAGIC - **Structural validation**: `_strict_validate()` rejects any config exceeding 100 slots before it reaches the API
# MAGIC
# MAGIC ### Arbiter Benchmark Corrections (Pre-Loop)
# MAGIC
# MAGIC > **📝 Note:** Before the adaptive loop begins, the harness runs `_extract_arbiter_actions_from_baseline()` to find rows where the arbiter verdict was `genie_correct` — meaning Genie's SQL was actually correct and the benchmark's expected SQL was wrong. When `genie_correct` verdicts meet or exceed `ARBITER_CORRECTION_TRIGGER` (default 3), `apply_benchmark_corrections()` rewrites those benchmarks' `expected_sql`. This prevents chasing false failures caused by stale gold SQL.
# MAGIC
# MAGIC ### Arbiter Verdict Filtering in Failure Clustering
# MAGIC
# MAGIC During each iteration, the harness filters out rows with arbiter verdict `genie_correct` before passing them to `cluster_failures()`. The optimizer only proposes fixes for questions where Genie is genuinely wrong.
# MAGIC
# MAGIC ### Reference SQL Tracking
# MAGIC
# MAGIC The harness extracts `reference_sqls` (question → SQL mapping) from the baseline iteration. These are passed to every evaluation call for cross-iteration SQL consistency tracking. When an iteration is accepted, reference SQLs are updated with new results.
# MAGIC
# MAGIC ### Noise Floor Adjustment for Gate Tolerances
# MAGIC
# MAGIC > **💡 Tip:** To prevent false regression signals on small benchmark sets, the harness computes: `noise_floor = 100.0 / max(len(benchmarks), 1)`. Gate tolerances are adjusted:
# MAGIC > - **Slice gate:** `effective_tolerance = max(SLICE_GATE_TOLERANCE, noise_floor + 2.0)`
# MAGIC > - **Full eval:** `effective_threshold = max(REGRESSION_THRESHOLD, noise_floor)`
# MAGIC >
# MAGIC > Example: 10 benchmarks → noise floor 10.0% → full eval threshold = `max(10.0, 10.0) = 10.0%`, slice gate = `max(15.0, 12.0) = 15.0%`.
# MAGIC
# MAGIC ### SQL Context (USE CATALOG / USE SCHEMA)
# MAGIC
# MAGIC Before each evaluation (slice, P0, full), the harness calls `_ensure_sql_context(spark, catalog, schema)`:
# MAGIC
# MAGIC ```sql
# MAGIC USE CATALOG `{catalog}`;
# MAGIC USE SCHEMA `{schema}`;
# MAGIC ```
# MAGIC
# MAGIC > **⚠️ Warning:** Without this, you may see "target schema not in current catalog" errors when the default session catalog differs from the Genie Space's UC location.
# MAGIC
# MAGIC ### MLflow Labeling Session
# MAGIC
# MAGIC At the end of the loop, a labeling session is created for human review via `create_review_session()`. Traces from evaluation runs are populated into the session, and the session URL is persisted to Delta and surfaced in the UI. Expected SQL is logged on each trace via `mlflow.log_expectation()` so reviewers can see the ground truth alongside generated SQL.
# MAGIC
# MAGIC ### What `thresholds_met` Means
# MAGIC
# MAGIC `thresholds_met` is a boolean from Task 2 (baseline_eval). It is `True` when `all_thresholds_met(scores, DEFAULT_THRESHOLDS)` returns `True` — i.e., every quality dimension meets its target threshold. When `True`, the lever loop is skipped.

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🚪 Baseline Gate: Skip If Thresholds Already Met
# MAGIC
# MAGIC > **📝 Note:** Even if this task runs (e.g. due to job configuration), we check `thresholds_met` at the start. If the baseline already meets all quality thresholds, we publish baseline values as-is and exit early — no lever iterations needed.
# MAGIC
# MAGIC On skip:
# MAGIC - Publish baseline scores, accuracy, model_id as the final result
# MAGIC - Set `iteration_counter=0`, `skipped=True`
# MAGIC - Exit with `dbutils.notebook.exit("SKIPPED: baseline meets thresholds")`

# COMMAND ----------

import json
import traceback
from functools import partial
from typing import Any, cast

from databricks.sdk import WorkspaceClient
from pyspark.sql import SparkSession

from genie_space_optimizer.jobs._helpers import _banner as _banner_base
from genie_space_optimizer.jobs._helpers import _log as _log_base
from genie_space_optimizer.optimization.evaluation import load_benchmarks_from_dataset
from genie_space_optimizer.optimization.harness import _run_lever_loop

dbutils = cast(Any, globals().get("dbutils"))

_TASK_LABEL = "TASK-4 LEVER_LOOP"
_banner = partial(_banner_base, _TASK_LABEL)
_log = partial(_log_base, _TASK_LABEL)

# COMMAND ----------

# MAGIC %md
# MAGIC ## ⚙️ Reading Upstream Task Values
# MAGIC
# MAGIC Task 4 reads from three upstream tasks:
# MAGIC
# MAGIC | Source | Keys | Purpose |
# MAGIC |--------|------|---------|
# MAGIC | `preflight` | `run_id`, `space_id`, `domain`, `catalog`, `schema` | Run and UC context |
# MAGIC | `preflight` | `experiment_name` | MLflow experiment for evaluations |
# MAGIC | `preflight` | `max_iterations` | Cap on lever loop iterations |
# MAGIC | `preflight` | `levers` | Lever indices to try (default `[1,2,3,4,5]`) |
# MAGIC | `preflight` | `apply_mode` | Where levers 1–3 write: `genie_config`, `uc_artifact`, or `both` |
# MAGIC | `baseline_eval` | `scores` | Per-judge scores (JSON) |
# MAGIC | `baseline_eval` | `overall_accuracy` | Aggregate accuracy |
# MAGIC | `baseline_eval` | `thresholds_met` | `True` if baseline already meets all quality thresholds |
# MAGIC | `baseline_eval` | `model_id` | Genie model version ID for iteration 0 |
# MAGIC | `enrichment` | `enrichment_model_id` | LoggedModel snapshot of enriched Genie Space |
# MAGIC | `enrichment` | `enrichment_skipped` | Whether enrichment was skipped (baseline met thresholds) |

# COMMAND ----------

w = WorkspaceClient()
spark = SparkSession.builder.getOrCreate()

# Read task values from upstream
run_id = dbutils.jobs.taskValues.get(taskKey="preflight", key="run_id")
space_id = dbutils.jobs.taskValues.get(taskKey="preflight", key="space_id")
domain = dbutils.jobs.taskValues.get(taskKey="preflight", key="domain")
catalog = dbutils.jobs.taskValues.get(taskKey="preflight", key="catalog")
schema = dbutils.jobs.taskValues.get(taskKey="preflight", key="schema")
exp_name = dbutils.jobs.taskValues.get(taskKey="preflight", key="experiment_name")
max_iterations = int(dbutils.jobs.taskValues.get(taskKey="preflight", key="max_iterations"))
levers = json.loads(dbutils.jobs.taskValues.get(taskKey="preflight", key="levers"))
apply_mode = dbutils.jobs.taskValues.get(taskKey="preflight", key="apply_mode")

import os as _os
_warehouse_id = dbutils.jobs.taskValues.get(taskKey="preflight", key="warehouse_id", default="")
if _warehouse_id:
    _os.environ["GENIE_SPACE_OPTIMIZER_WAREHOUSE_ID"] = _warehouse_id

triggered_by = dbutils.jobs.taskValues.get(taskKey="preflight", key="triggered_by", default="")
human_corrections = json.loads(dbutils.jobs.taskValues.get(taskKey="preflight", key="human_corrections", default="[]"))

scores_json = dbutils.jobs.taskValues.get(taskKey="baseline_eval", key="scores")
prev_scores = json.loads(scores_json)
prev_accuracy = float(dbutils.jobs.taskValues.get(taskKey="baseline_eval", key="overall_accuracy"))
thresholds_met_raw = dbutils.jobs.taskValues.get(taskKey="baseline_eval", key="thresholds_met")
thresholds_met = str(thresholds_met_raw).lower() in ("true", "1")
prev_model_id = dbutils.jobs.taskValues.get(taskKey="baseline_eval", key="model_id")

enrichment_model_id = dbutils.jobs.taskValues.get(taskKey="enrichment", key="enrichment_model_id")
enrichment_skipped_raw = dbutils.jobs.taskValues.get(taskKey="enrichment", key="enrichment_skipped")
enrichment_skipped = str(enrichment_skipped_raw).lower() in ("true", "1")

import mlflow
mlflow.set_experiment(exp_name)

_banner("Resolved Upstream Task Values")
_log(
    "Inputs",
    run_id=run_id,
    space_id=space_id,
    domain=domain,
    catalog=catalog,
    schema=schema,
    experiment_name=exp_name,
    max_iterations=max_iterations,
    levers=levers,
    apply_mode=apply_mode,
    baseline_accuracy=prev_accuracy,
    baseline_thresholds_met=thresholds_met,
    baseline_model_id=prev_model_id,
    enrichment_model_id=enrichment_model_id,
    enrichment_skipped=enrichment_skipped,
    triggered_by=triggered_by,
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🚪 Baseline Gate Check
# MAGIC
# MAGIC > **📝 Note:** If `thresholds_met` is `True`, we skip the lever loop and publish baseline values as the final result. Downstream tasks (finalize, deploy) receive the same structure whether we skipped or ran the loop.

# COMMAND ----------

if thresholds_met:
    _banner("Baseline Gate: SKIP Lever Loop")
    _log("Skip reason", reason="baseline_meets_thresholds", baseline_accuracy=prev_accuracy)
    dbutils.jobs.taskValues.set(key="scores", value=scores_json)
    dbutils.jobs.taskValues.set(key="accuracy", value=prev_accuracy)
    dbutils.jobs.taskValues.set(key="model_id", value=prev_model_id)
    dbutils.jobs.taskValues.set(key="iteration_counter", value=0)
    dbutils.jobs.taskValues.set(key="skipped", value=True)
    dbutils.notebook.exit("SKIPPED: baseline meets thresholds")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🔄 Loading Benchmarks
# MAGIC
# MAGIC - **Benchmarks:** Loaded from `{catalog}.{schema}.genie_benchmarks_{domain}`.
# MAGIC
# MAGIC > **📝 Note:** Proactive enrichment (descriptions, joins, metadata, instructions, example SQLs) has already been applied by Task 3 (enrichment). The lever loop loads the enriched config directly from the Genie Space API.

# COMMAND ----------

uc_schema = f"{catalog}.{schema}"
benchmarks = load_benchmarks_from_dataset(spark, uc_schema, domain)
benchmarks = [b for b in benchmarks if b.get("split") != "held_out"]
_banner("Loaded Benchmarks")
_log("Benchmark dataset (train only)", uc_schema=uc_schema, domain=domain, benchmark_count=len(benchmarks))
if not benchmarks:
    raise RuntimeError(f"No benchmarks found in {uc_schema}.genie_benchmarks_{domain}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🔧 Adaptive Lever Loop
# MAGIC
# MAGIC The core optimization loop. Each iteration:
# MAGIC 1. Re-cluster failures from the latest evaluation
# MAGIC 2. Rank clusters by `cluster_impact()` (causal weight × severity × fixability)
# MAGIC 3. Call the LLM strategist to propose exactly 1 action group
# MAGIC 4. Apply patches and run 3-gate evaluation (slice → P0 → full)
# MAGIC 5. Accept (if accuracy improves) or rollback (if regression)
# MAGIC 6. Build reflection entry for the next iteration's context
# MAGIC 7. Check convergence (thresholds met, diminishing returns, no clusters left)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Optimization Summary
# MAGIC
# MAGIC After the loop completes, print a comprehensive summary comparing baseline
# MAGIC vs. final accuracy, listing all iterations, and accepted/rolled-back levers.

# COMMAND ----------

try:
    _banner("Running _run_lever_loop (enrichment already done by Task 3)")
    loop_out = _run_lever_loop(
        w, spark, run_id, space_id, domain, benchmarks, exp_name,
        prev_scores, prev_accuracy, prev_model_id, {},
        catalog, schema, levers, max_iterations,
        apply_mode=apply_mode,
        triggered_by=triggered_by,
        human_corrections=human_corrections,
        enrichment_done=True,
        enrichment_model_id=enrichment_model_id,
    )
    _log(
        "Lever loop finished",
        accuracy=loop_out["accuracy"],
        iteration_counter=loop_out["iteration_counter"],
        best_iteration=loop_out["best_iteration"],
        levers_attempted=loop_out["levers_attempted"],
        levers_accepted=loop_out["levers_accepted"],
        levers_rolled_back=loop_out["levers_rolled_back"],
    )
except Exception as exc:
    _banner("Lever Loop FAILED")
    _log(
        "Failure details",
        error_type=type(exc).__name__,
        error_message=str(exc),
        traceback=traceback.format_exc(),
    )
    raise

# COMMAND ----------

# MAGIC %md
# MAGIC ## 📤 Publishing Task Values
# MAGIC
# MAGIC Task 5 (finalize) and Task 6 (deploy) consume these values. The keys must match what downstream notebooks expect.

# COMMAND ----------

_banner("Publishing Task Values")
dbutils.jobs.taskValues.set(key="scores", value=json.dumps(loop_out["scores"]))
dbutils.jobs.taskValues.set(key="accuracy", value=loop_out["accuracy"])
dbutils.jobs.taskValues.set(key="model_id", value=loop_out["model_id"])
dbutils.jobs.taskValues.set(key="iteration_counter", value=loop_out["iteration_counter"])
dbutils.jobs.taskValues.set(key="best_iteration", value=loop_out["best_iteration"])
dbutils.jobs.taskValues.set(key="skipped", value=False)

debug_info = {
    k: v for k, v in loop_out.items()
    if k.startswith("_debug_") or k in ("levers_attempted", "levers_accepted", "levers_rolled_back", "iteration_counter")
}
dbutils.jobs.taskValues.set(key="debug_info", value=json.dumps(debug_info, default=str))

_log(
    "Task values published",
    accuracy=loop_out["accuracy"],
    model_id=loop_out["model_id"],
    iteration_counter=loop_out["iteration_counter"],
    debug_info=debug_info,
)
_banner("Task 4 Completed")
dbutils.notebook.exit(json.dumps(debug_info, default=str))

# COMMAND ----------

# MAGIC %md
# MAGIC ## ✅ What Success Looks Like
# MAGIC
# MAGIC When this task completes successfully (iterations accepted), you will see output similar to:
# MAGIC
# MAGIC ```
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] Running _run_lever_loop
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] ADAPTIVE STRATEGIST -- Iteration 1
# MAGIC   Clusters: 5 hard failures, 2 soft signals
# MAGIC   Top cluster: wrong_table (impact 12.5, 3 questions)
# MAGIC [TASK-4 LEVER_LOOP] AG applied: 3 patches (Lever 1: 2, Lever 5: 1)
# MAGIC [TASK-4 LEVER_LOOP] Slice gate: PASSED
# MAGIC [TASK-4 LEVER_LOOP] Full eval: PASSED (accuracy 72.5% -> 78.0%)
# MAGIC [TASK-4 LEVER_LOOP] Iteration 1: ACCEPTED
# MAGIC [TASK-4 LEVER_LOOP] ADAPTIVE STRATEGIST -- Iteration 2
# MAGIC   Reflection: Iter 1 accepted +5.5%, wrong_table fixed
# MAGIC   Clusters: 3 hard failures remaining
# MAGIC [TASK-4 LEVER_LOOP] AG applied: 2 patches (Lever 5: 2)
# MAGIC [TASK-4 LEVER_LOOP] Slice gate: FAILED (regression -1.2%)
# MAGIC [TASK-4 LEVER_LOOP] Iteration 2: ROLLED BACK
# MAGIC [TASK-4 LEVER_LOOP] ADAPTIVE STRATEGIST -- Iteration 3
# MAGIC   Reflection: Iter 2 rolled back, avoid example_sql for ambiguous questions
# MAGIC   Clusters: 3 hard failures remaining
# MAGIC ...
# MAGIC [TASK-4 LEVER_LOOP] OPTIMIZATION RUN SUMMARY
# MAGIC   Baseline accuracy: 72.5%
# MAGIC   Final accuracy: 85.0%
# MAGIC   Iterations: 3 attempted, 2 accepted, 1 rolled back
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] Task 4 Completed
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC ```
# MAGIC
# MAGIC When the baseline gate triggers a skip:
# MAGIC
# MAGIC ```
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] Baseline Gate: SKIP Lever Loop
# MAGIC ════════════════════════════════════════════════════════════════
# MAGIC [TASK-4 LEVER_LOOP] Skip reason
# MAGIC   {"reason": "baseline_meets_thresholds", "baseline_accuracy": 95.2}
# MAGIC ```
# MAGIC
# MAGIC ## 📋 Summary
# MAGIC
# MAGIC Task 4 (Lever Loop) is a **thin wrapper** around `_run_lever_loop()` with `enrichment_done=True`.
# MAGIC Proactive enrichment (descriptions, joins, metadata, instructions, example SQLs) is handled by
# MAGIC Task 3 (enrichment). The lever loop loads the enriched config from the Genie Space API and runs
# MAGIC the adaptive optimization engine: re-clustering failures, scoring by impact, calling the strategist
# MAGIC for 1 action group per iteration, applying patches via 3-gate evaluation (slice → P0 → full),
# MAGIC and reflecting on outcomes to guide future iterations.
# MAGIC
# MAGIC All business logic lives in the harness (`optimization/harness.py`), shared identically by
# MAGIC the DAG notebooks and the `optimize_genie_space()` convenience function.
