"""
Delta-backed state machine for Genie Space optimization runs.

Persists every stage transition, iteration score, and patch record
across 5 Delta tables. Both the optimization harness (writer) and
the FastAPI backend (reader) depend on this module.

All functions accept ``spark``, ``catalog``, and ``schema`` as explicit
arguments — no globals.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

import pandas as pd

from genie_space_optimizer.common.config import (
    TABLE_ASI,
    TABLE_ITERATIONS,
    TABLE_PATCHES,
    TABLE_RUNS,
    TABLE_STAGES,
)
from genie_space_optimizer.common.delta_helpers import (
    _fqn,
    insert_row,
    read_table,
    run_query,
    update_row,
)

if TYPE_CHECKING:
    from pyspark.sql import SparkSession

logger = logging.getLogger(__name__)

# ── DDL Constants ────────────────────────────────────────────────────────

_GENIE_OPT_RUNS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_runs (
    run_id              STRING        NOT NULL COMMENT 'UUID for this optimization run',
    space_id            STRING        NOT NULL COMMENT 'Genie Space ID being optimized',
    domain              STRING        NOT NULL COMMENT 'Domain name (e.g. revenue_property)',
    catalog             STRING        NOT NULL COMMENT 'Unity Catalog name',
    uc_schema           STRING        NOT NULL COMMENT 'UC schema (catalog.schema format)',
    status              STRING        NOT NULL COMMENT 'QUEUED|IN_PROGRESS|CONVERGED|STALLED|MAX_ITERATIONS|FAILED|CANCELLED',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When the run was created',
    completed_at        TIMESTAMP              COMMENT 'When the run reached a terminal state',
    job_run_id          STRING                 COMMENT 'Databricks Job run ID',
    job_id              STRING                 COMMENT 'Databricks Job definition ID',
    max_iterations      INT           NOT NULL COMMENT 'Maximum lever iterations allowed',
    levers              STRING        NOT NULL COMMENT 'JSON array of lever numbers to try, e.g. [1,2,3,4,5]',
    apply_mode          STRING        NOT NULL COMMENT 'Where patches are applied: genie_config|uc_artifact|both',
    deploy_target       STRING                 COMMENT 'DABs target for post-optimization deploy (null = no deploy)',
    benchmarks_generated BOOLEAN                COMMENT 'True if benchmarks were auto-generated by LLM during this run',
    best_iteration      INT                    COMMENT 'Iteration number with highest accuracy',
    best_accuracy       DOUBLE                 COMMENT 'Best overall accuracy achieved (0-100)',
    best_repeatability  DOUBLE                 COMMENT 'Best repeatability percentage (0-100)',
    best_model_id       STRING                 COMMENT 'MLflow LoggedModel ID for the best iteration',
    convergence_reason  STRING                 COMMENT 'Why the run stopped (threshold_met|plateau|max_iterations|error)',
    experiment_name     STRING                 COMMENT 'MLflow experiment path',
    experiment_id       STRING                 COMMENT 'MLflow experiment ID',
    config_snapshot     STRING                 COMMENT 'JSON: Genie Space config at run start',
    triggered_by        STRING                 COMMENT 'User email who initiated the run',
    updated_at          TIMESTAMP     NOT NULL COMMENT 'Last update timestamp'
)
USING DELTA
PARTITIONED BY (space_id)
COMMENT 'Genie Space optimization runs - one row per optimization attempt'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)"""

_GENIE_OPT_STAGES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_stages (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    task_key            STRING                 COMMENT 'Databricks Job task key (preflight, baseline_eval, lever_loop, finalize, deploy)',
    stage               STRING        NOT NULL COMMENT 'Stage name (PREFLIGHT_STARTED, LEVER_2_EVAL_DONE, etc.)',
    status              STRING        NOT NULL COMMENT 'STARTED|COMPLETE|FAILED|SKIPPED|ROLLED_BACK',
    started_at          TIMESTAMP     NOT NULL COMMENT 'When this stage began',
    completed_at        TIMESTAMP              COMMENT 'When this stage ended (null if in progress)',
    duration_seconds    DOUBLE                 COMMENT 'Wall-clock duration of this stage',
    lever               INT                    COMMENT 'Lever number (1-5) if this is a lever stage, null otherwise',
    iteration           INT                    COMMENT 'Evaluation iteration number if applicable',
    detail_json         STRING                 COMMENT 'JSON: stage-specific detail',
    error_message       STRING                 COMMENT 'Error message if status=FAILED'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Optimization stage transitions - ordered timeline of what happened'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)"""

_GENIE_OPT_ITERATIONS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_iterations (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Evaluation iteration number (0 = baseline)',
    lever               INT                    COMMENT 'Which lever was applied before this eval (null for baseline)',
    eval_scope          STRING        NOT NULL COMMENT 'full|slice|p0|held_out',
    timestamp           TIMESTAMP     NOT NULL COMMENT 'When this evaluation completed',
    mlflow_run_id       STRING                 COMMENT 'MLflow run ID for this evaluation',
    model_id            STRING                 COMMENT 'LoggedModel ID used for this evaluation',
    overall_accuracy    DOUBLE        NOT NULL COMMENT 'Overall accuracy percentage (0-100)',
    total_questions     INT           NOT NULL COMMENT 'Number of benchmark questions evaluated',
    correct_count       INT           NOT NULL COMMENT 'Number of questions that passed all judges',
    scores_json         STRING        NOT NULL COMMENT 'JSON: per-judge scores',
    failures_json       STRING                 COMMENT 'JSON: array of failed question IDs',
    remaining_failures  STRING                 COMMENT 'JSON: array of question IDs still failing',
    arbiter_actions_json STRING                COMMENT 'JSON: array of arbiter verdicts',
    repeatability_pct   DOUBLE                 COMMENT 'Repeatability percentage (0-100) if measured',
    repeatability_json  STRING                 COMMENT 'JSON: per-question repeatability details',
    thresholds_met      BOOLEAN       NOT NULL COMMENT 'True if all quality thresholds passed',
    rows_json           STRING                 COMMENT 'JSON: per-question evaluation detail rows'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Evaluation iteration results - scores and failures per eval pass'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)"""

_GENIE_OPT_PATCHES_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_patches (
    run_id              STRING        NOT NULL COMMENT 'FK to genie_opt_runs.run_id',
    iteration           INT           NOT NULL COMMENT 'Iteration when this patch was applied',
    lever               INT           NOT NULL COMMENT 'Lever number (1-5)',
    patch_index         INT           NOT NULL COMMENT 'Index within the patch set',
    patch_type          STRING        NOT NULL COMMENT 'Patch type from PATCH_TYPES',
    scope               STRING        NOT NULL COMMENT 'genie_config or uc_artifact or both',
    risk_level          STRING        NOT NULL COMMENT 'low|medium|high',
    target_object       STRING                 COMMENT 'Object being modified (table name, column name, etc.)',
    patch_json          STRING        NOT NULL COMMENT 'JSON: full patch definition',
    command_json        STRING                 COMMENT 'JSON: rendered action command',
    rollback_json       STRING                 COMMENT 'JSON: rollback command',
    applied_at          TIMESTAMP     NOT NULL COMMENT 'When the patch was applied',
    rolled_back         BOOLEAN                COMMENT 'True if this patch was subsequently rolled back',
    rolled_back_at      TIMESTAMP              COMMENT 'When the rollback occurred',
    rollback_reason     STRING                 COMMENT 'Why the patch was rolled back',
    proposal_id         STRING                 COMMENT 'FK to the proposal that generated this patch',
    cluster_id          STRING                 COMMENT 'Failure cluster that motivated this patch'
)
USING DELTA
PARTITIONED BY (run_id)
COMMENT 'Patch audit trail - every metadata change applied to Genie Space'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)"""

_GENIE_EVAL_ASI_RESULTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_eval_asi_results (
    run_id              STRING        NOT NULL COMMENT 'MLflow run ID',
    iteration           INT           NOT NULL COMMENT 'Evaluation iteration number',
    question_id         STRING        NOT NULL COMMENT 'Benchmark question ID',
    judge               STRING        NOT NULL COMMENT 'Judge name',
    value               STRING        NOT NULL COMMENT 'Judge verdict (yes|no|skipped|genie_correct|...)',
    failure_type        STRING                 COMMENT 'From FAILURE_TAXONOMY',
    severity            STRING                 COMMENT 'critical|major|minor|info',
    confidence          DOUBLE                 COMMENT 'Judge confidence (0.0-1.0)',
    blame_set           STRING                 COMMENT 'JSON: array of metadata fields blamed',
    counterfactual_fix  STRING                 COMMENT 'Suggested metadata change to fix the issue',
    wrong_clause        STRING                 COMMENT 'SQL clause that is wrong',
    expected_value      STRING                 COMMENT 'What the correct value should be',
    actual_value        STRING                 COMMENT 'What Genie actually produced',
    missing_metadata    STRING                 COMMENT 'What metadata should exist but does not',
    ambiguity_detected  BOOLEAN                COMMENT 'True if the question is ambiguous',
    logged_at           TIMESTAMP     NOT NULL COMMENT 'When this ASI row was written'
)
USING DELTA
COMMENT 'Actionable Side Information from evaluation judges'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)"""

TABLE_DATA_ACCESS_GRANTS = "genie_opt_data_access_grants"

_GENIE_OPT_DATA_ACCESS_GRANTS_DDL = """\
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.genie_opt_data_access_grants (
    grant_id            STRING        NOT NULL COMMENT 'UUID for this grant record',
    target_catalog      STRING        NOT NULL COMMENT 'Catalog the SP was granted access to',
    target_schema       STRING        NOT NULL COMMENT 'Schema the SP was granted access to',
    granted_by          STRING        NOT NULL COMMENT 'User who performed the grant',
    granted_at          TIMESTAMP     NOT NULL COMMENT 'When the grant was applied',
    revoked_at          TIMESTAMP              COMMENT 'When the grant was revoked (null if active)',
    status              STRING        NOT NULL COMMENT 'active|revoked'
)
USING DELTA
COMMENT 'Tracks UC privileges granted to the app SP for reading Genie space assets'
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
)"""

_ALL_DDL: dict[str, str] = {
    TABLE_RUNS: _GENIE_OPT_RUNS_DDL,
    TABLE_STAGES: _GENIE_OPT_STAGES_DDL,
    TABLE_ITERATIONS: _GENIE_OPT_ITERATIONS_DDL,
    TABLE_PATCHES: _GENIE_OPT_PATCHES_DDL,
    TABLE_ASI: _GENIE_EVAL_ASI_RESULTS_DDL,
    TABLE_DATA_ACCESS_GRANTS: _GENIE_OPT_DATA_ACCESS_GRANTS_DDL,
}


# ── Table Bootstrapping ─────────────────────────────────────────────────


def ensure_optimization_tables(spark: SparkSession, catalog: str, schema: str) -> None:
    """Create all optimization Delta tables if they don't exist (idempotent)."""
    for name, ddl in _ALL_DDL.items():
        resolved = ddl.replace("{catalog}", catalog).replace("{schema}", schema)
        spark.sql(resolved)
        logger.info("  [OK] %s.%s.%s", catalog, schema, name)

    _migrate_add_columns(spark, catalog, schema)


def _migrate_add_columns(spark: SparkSession, catalog: str, schema: str) -> None:
    """Add columns introduced after initial DDL (safe to run repeatedly)."""
    migrations = [
        (TABLE_RUNS, "job_id", "STRING COMMENT 'Databricks Job definition ID'"),
    ]
    for table, col, col_def in migrations:
        fqn = _fqn(catalog, schema, table)
        try:
            spark.sql(f"ALTER TABLE {fqn} ADD COLUMN {col} {col_def}")
            logger.info("  [MIGRATED] Added %s.%s", fqn, col)
        except Exception as exc:
            if "already exists" in str(exc).lower():
                logger.debug("  [SKIP] %s.%s already exists", fqn, col)
            else:
                logger.warning("  [WARN] Could not add %s.%s: %s", fqn, col, exc)


# ── Write Functions ──────────────────────────────────────────────────────


def create_run(
    spark: SparkSession,
    run_id: str,
    space_id: str,
    domain: str,
    catalog: str,
    schema: str,
    *,
    uc_schema: str | None = None,
    max_iterations: int = 5,
    levers: list[int] | None = None,
    apply_mode: str = "genie_config",
    deploy_target: str | None = None,
    experiment_name: str | None = None,
    experiment_id: str | None = None,
    config_snapshot: dict | None = None,
    triggered_by: str | None = None,
) -> None:
    """Insert a new row into ``genie_opt_runs`` with status QUEUED."""
    from genie_space_optimizer.common.config import DEFAULT_LEVER_ORDER, MAX_ITERATIONS

    now = datetime.now(timezone.utc).isoformat()
    row: dict[str, Any] = {
        "run_id": run_id,
        "space_id": space_id,
        "domain": domain,
        "catalog": catalog,
        "uc_schema": uc_schema or f"{catalog}.{schema}",
        "status": "QUEUED",
        "started_at": now,
        "max_iterations": max_iterations or MAX_ITERATIONS,
        "levers": json.dumps(levers or DEFAULT_LEVER_ORDER),
        "apply_mode": apply_mode,
        "updated_at": now,
    }
    if deploy_target is not None:
        row["deploy_target"] = deploy_target
    if experiment_name is not None:
        row["experiment_name"] = experiment_name
    if experiment_id is not None:
        row["experiment_id"] = experiment_id
    if config_snapshot is not None:
        row["config_snapshot"] = json.dumps(config_snapshot)
    if triggered_by is not None:
        row["triggered_by"] = triggered_by

    insert_row(spark, catalog, schema, TABLE_RUNS, row)
    logger.info("Created run %s for space %s", run_id, space_id)


def update_run_status(
    spark: SparkSession,
    run_id: str,
    catalog: str,
    schema: str,
    *,
    status: str | None = None,
    best_iteration: int | None = None,
    best_accuracy: float | None = None,
    best_repeatability: float | None = None,
    best_model_id: str | None = None,
    convergence_reason: str | None = None,
    job_run_id: str | None = None,
    job_id: str | None = None,
    experiment_name: str | None = None,
    experiment_id: str | None = None,
) -> None:
    """Update ``genie_opt_runs`` — only sets non-None fields."""
    now = datetime.now(timezone.utc).isoformat()

    updates: dict[str, Any] = {"updated_at": now}
    terminal_statuses = {"CONVERGED", "STALLED", "MAX_ITERATIONS", "FAILED", "CANCELLED"}

    if status is not None:
        updates["status"] = status
        if status in terminal_statuses:
            updates["completed_at"] = now
    if best_iteration is not None:
        updates["best_iteration"] = best_iteration
    if best_accuracy is not None:
        updates["best_accuracy"] = best_accuracy
    if best_repeatability is not None:
        updates["best_repeatability"] = best_repeatability
    if best_model_id is not None:
        updates["best_model_id"] = best_model_id
    if convergence_reason is not None:
        updates["convergence_reason"] = convergence_reason
    if job_run_id is not None:
        updates["job_run_id"] = job_run_id
    if job_id is not None:
        updates["job_id"] = job_id
    if experiment_name is not None:
        updates["experiment_name"] = experiment_name
    if experiment_id is not None:
        updates["experiment_id"] = experiment_id

    update_row(spark, catalog, schema, TABLE_RUNS, {"run_id": run_id}, updates)


def write_stage(
    spark: SparkSession,
    run_id: str,
    stage: str,
    status: str,
    *,
    task_key: str | None = None,
    lever: int | None = None,
    iteration: int | None = None,
    detail: dict | None = None,
    error_message: str | None = None,
    catalog: str,
    schema: str,
) -> None:
    """Insert into ``genie_opt_stages``.

    ``task_key`` identifies which Databricks Job task wrote this row.
    ``detail`` dict is JSON-serialized into ``detail_json``.
    For COMPLETE/FAILED/SKIPPED/ROLLED_BACK, computes ``duration_seconds``
    by diffing the matching STARTED row's ``started_at``.
    """
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()
    fqn = _fqn(catalog, schema, TABLE_STAGES)

    completed_at: str | None = None
    duration_seconds: float | None = None

    if status in ("COMPLETE", "FAILED", "SKIPPED", "ROLLED_BACK"):
        completed_at = now_iso
        started_df = run_query(
            spark,
            f"SELECT started_at FROM {fqn} "
            f"WHERE run_id = '{run_id}' AND stage = '{stage}' AND status = 'STARTED' "
            f"ORDER BY started_at DESC LIMIT 1",
        )
        if not started_df.empty:
            started_ts = pd.Timestamp(started_df.iloc[0]["started_at"])
            if started_ts.tzinfo is None:
                started_ts = started_ts.tz_localize("UTC")
            duration_seconds = (now - started_ts.to_pydatetime()).total_seconds()

    detail_json = json.dumps(detail) if detail else None
    _safe_err = error_message.replace("'", "''") if error_message else None

    col_names = (
        "run_id, task_key, stage, status, started_at, completed_at, "
        "duration_seconds, lever, iteration, detail_json, error_message"
    )

    def _sql_val(val: Any) -> str:
        if val is None:
            return "NULL"
        if isinstance(val, bool):
            return str(val).lower()
        if isinstance(val, (int, float)):
            return str(val)
        return f"'{val}'"

    vals = ", ".join(
        [
            _sql_val(run_id),
            _sql_val(task_key),
            _sql_val(stage),
            _sql_val(status),
            f"TIMESTAMP '{now_iso}'",
            f"TIMESTAMP '{completed_at}'" if completed_at else "NULL",
            _sql_val(duration_seconds),
            _sql_val(lever),
            _sql_val(iteration),
            _sql_val(detail_json.replace("'", "''") if detail_json else None),
            _sql_val(_safe_err),
        ]
    )

    spark.sql(f"INSERT INTO {fqn} ({col_names}) VALUES ({vals})")
    logger.info("Stage %s/%s for run %s", stage, status, run_id)


def write_iteration(
    spark: SparkSession,
    run_id: str,
    iteration: int,
    eval_result: dict,
    *,
    catalog: str,
    schema: str,
    lever: int | None = None,
    eval_scope: str = "full",
    model_id: str | None = None,
) -> None:
    """Insert into ``genie_opt_iterations`` with scores, failures, etc."""
    now = datetime.now(timezone.utc).isoformat()
    fqn = _fqn(catalog, schema, TABLE_ITERATIONS)

    scores = eval_result.get("scores", {})
    failures = eval_result.get("failures", [])
    remaining = eval_result.get("remaining_failures", failures)
    arbiter_actions = eval_result.get("arbiter_actions", [])
    thresholds_met = eval_result.get("thresholds_met", False)
    if isinstance(thresholds_met, (int, float)):
        thresholds_met = thresholds_met == 1.0

    repeatability_pct = eval_result.get("repeatability_pct")
    repeatability_details = eval_result.get("repeatability_details")
    rows_data = eval_result.get("rows")
    if isinstance(rows_data, list):
        _STRIP_COLS = {"trace", "trace_id"}
        rows_data = [{k: v for k, v in r.items() if k not in _STRIP_COLS} for r in rows_data if isinstance(r, dict)]

    def _esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace("'", "''")

    def _opt_json(val: Any) -> str:
        if val is None:
            return "NULL"
        return f"'{_esc(json.dumps(val))}'"

    mlflow_run_id = eval_result.get("mlflow_run_id")

    col_names = (
        "run_id, iteration, lever, eval_scope, timestamp, mlflow_run_id, model_id, "
        "overall_accuracy, total_questions, correct_count, scores_json, failures_json, "
        "remaining_failures, arbiter_actions_json, repeatability_pct, repeatability_json, "
        "thresholds_met, rows_json"
    )
    vals = ", ".join(
        [
            f"'{run_id}'",
            str(iteration),
            str(lever) if lever is not None else "NULL",
            f"'{eval_scope}'",
            f"TIMESTAMP '{now}'",
            f"'{mlflow_run_id}'" if mlflow_run_id else "NULL",
            f"'{model_id}'" if model_id else "NULL",
            str(eval_result.get("overall_accuracy", 0.0)),
            str(eval_result.get("total_questions", 0)),
            str(eval_result.get("correct_count", 0)),
            f"'{_esc(json.dumps(scores))}'",
            _opt_json(failures),
            _opt_json(remaining),
            _opt_json(arbiter_actions),
            str(repeatability_pct) if repeatability_pct is not None else "NULL",
            _opt_json(repeatability_details),
            str(thresholds_met).lower(),
            _opt_json(rows_data),
        ]
    )

    spark.sql(f"INSERT INTO {fqn} ({col_names}) VALUES ({vals})")
    logger.info(
        "Iteration %d (lever=%s, scope=%s) for run %s: accuracy=%.1f%%",
        iteration,
        lever,
        eval_scope,
        run_id,
        eval_result.get("overall_accuracy", 0.0),
    )


def write_patch(
    spark: SparkSession,
    run_id: str,
    iteration: int,
    lever: int,
    patch_index: int,
    patch_record: dict,
    catalog: str,
    schema: str,
) -> None:
    """Insert into ``genie_opt_patches``."""
    now = datetime.now(timezone.utc).isoformat()

    def _esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace("'", "''")

    row: dict[str, Any] = {
        "run_id": run_id,
        "iteration": iteration,
        "lever": lever,
        "patch_index": patch_index,
        "patch_type": patch_record.get("patch_type", "unknown"),
        "scope": patch_record.get("scope", "genie_config"),
        "risk_level": patch_record.get("risk_level", "low"),
        "applied_at": now,
    }

    target_object = patch_record.get("target_object")
    if target_object is not None:
        row["target_object"] = target_object

    row["patch_json"] = json.dumps(patch_record.get("patch", patch_record))

    command = patch_record.get("command")
    if command is not None:
        row["command_json"] = json.dumps(command)

    rollback = patch_record.get("rollback")
    if rollback is not None:
        row["rollback_json"] = json.dumps(rollback)

    proposal_id = patch_record.get("proposal_id")
    if proposal_id is not None:
        row["proposal_id"] = proposal_id

    cluster_id = patch_record.get("cluster_id")
    if cluster_id is not None:
        row["cluster_id"] = cluster_id

    insert_row(spark, catalog, schema, TABLE_PATCHES, row)
    logger.info(
        "Patch %d (lever %d, iter %d) for run %s: %s on %s",
        patch_index,
        lever,
        iteration,
        run_id,
        row["patch_type"],
        target_object,
    )


def mark_patches_rolled_back(
    spark: SparkSession,
    run_id: str,
    iteration: int,
    reason: str,
    catalog: str,
    schema: str,
) -> None:
    """Set ``rolled_back=true`` on all patches for a given run + iteration."""
    now = datetime.now(timezone.utc).isoformat()
    fqn = _fqn(catalog, schema, TABLE_PATCHES)
    safe_reason = reason.replace("'", "''")
    spark.sql(
        f"UPDATE {fqn} SET rolled_back = true, "
        f"rolled_back_at = TIMESTAMP '{now}', "
        f"rollback_reason = '{safe_reason}' "
        f"WHERE run_id = '{run_id}' AND iteration = {iteration}"
    )
    logger.info("Rolled back patches for run %s iteration %d: %s", run_id, iteration, reason)


# ── Read Functions ───────────────────────────────────────────────────────


def load_run(spark: SparkSession, run_id: str, catalog: str, schema: str) -> dict | None:
    """Return a plain Python dict for a run, or ``None`` if not found."""
    df = read_table(spark, catalog, schema, TABLE_RUNS, filters={"run_id": run_id})
    if df.empty:
        return None
    row = df.iloc[0].to_dict()
    for col in ("levers", "config_snapshot"):
        if row.get(col) and isinstance(row[col], str):
            try:
                row[col] = json.loads(row[col])
            except (json.JSONDecodeError, TypeError):
                pass
    return row


def load_stages(spark: SparkSession, run_id: str, catalog: str, schema: str) -> pd.DataFrame:
    """All stages for a run, ordered by ``started_at ASC``."""
    fqn = _fqn(catalog, schema, TABLE_STAGES)
    return run_query(
        spark,
        f"SELECT * FROM {fqn} WHERE run_id = '{run_id}' ORDER BY started_at ASC",
    )


def load_iterations(spark: SparkSession, run_id: str, catalog: str, schema: str) -> pd.DataFrame:
    """All iterations for a run, ordered by ``iteration ASC``."""
    fqn = _fqn(catalog, schema, TABLE_ITERATIONS)
    return run_query(
        spark,
        f"SELECT * FROM {fqn} WHERE run_id = '{run_id}' ORDER BY iteration ASC",
    )


def load_patches(spark: SparkSession, run_id: str, catalog: str, schema: str) -> pd.DataFrame:
    """All patches for a run, ordered by ``applied_at ASC``."""
    fqn = _fqn(catalog, schema, TABLE_PATCHES)
    return run_query(
        spark,
        f"SELECT * FROM {fqn} WHERE run_id = '{run_id}' ORDER BY applied_at ASC",
    )


def read_latest_stage(
    spark: SparkSession, run_id: str, catalog: str, schema: str
) -> dict | None:
    """Return the most recent stage row as a dict, or ``None``."""
    fqn = _fqn(catalog, schema, TABLE_STAGES)
    df = run_query(
        spark,
        f"SELECT * FROM {fqn} WHERE run_id = '{run_id}' "
        f"ORDER BY started_at DESC LIMIT 1",
    )
    if df.empty:
        return None
    row = df.iloc[0].to_dict()
    if row.get("detail_json") and isinstance(row["detail_json"], str):
        try:
            row["detail"] = json.loads(row["detail_json"])
        except (json.JSONDecodeError, TypeError):
            pass
    return row


def load_latest_full_iteration(
    spark: SparkSession, run_id: str, catalog: str, schema: str
) -> dict | None:
    """Latest iteration with ``eval_scope='full'``. Used for resume + convergence."""
    fqn = _fqn(catalog, schema, TABLE_ITERATIONS)
    df = run_query(
        spark,
        f"SELECT * FROM {fqn} WHERE run_id = '{run_id}' AND eval_scope = 'full' "
        f"ORDER BY iteration DESC LIMIT 1",
    )
    if df.empty:
        return None
    row = df.iloc[0].to_dict()
    for col in ("scores_json", "failures_json", "remaining_failures", "arbiter_actions_json",
                "repeatability_json", "rows_json"):
        if row.get(col) and isinstance(row[col], str):
            try:
                row[col] = json.loads(row[col])
            except (json.JSONDecodeError, TypeError):
                pass
    return row


def load_runs_for_space(
    spark: SparkSession, space_id: str, catalog: str, schema: str
) -> pd.DataFrame:
    """All runs for a Genie Space, ordered by ``started_at DESC``."""
    fqn = _fqn(catalog, schema, TABLE_RUNS)
    return run_query(
        spark,
        f"SELECT * FROM {fqn} WHERE space_id = '{space_id}' ORDER BY started_at DESC",
    )


def load_recent_activity(
    spark: SparkSession,
    catalog: str,
    schema: str,
    *,
    space_id: str | None = None,
    limit: int = 20,
) -> pd.DataFrame:
    """Recent runs across the workspace (or for a single space).

    Used by the Dashboard view.
    """
    fqn = _fqn(catalog, schema, TABLE_RUNS)
    where = f"WHERE space_id = '{space_id}'" if space_id else ""
    return run_query(
        spark,
        f"SELECT * FROM {fqn} {where} ORDER BY started_at DESC LIMIT {limit}",
    )
