"use client";

import { motion } from "motion/react";
import { StageScreen } from "../StageScreen";
import { AnimatedChecklist } from "../shared/AnimatedChecklist";
import { DataModelCard } from "../shared/DataModelCard";
import {
  BENCHMARK_MODEL_FIELDS,
  FICTIONAL_EXAMPLE,
} from "../data";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

const LLM_CONTEXT_BLOCKS = [
  "domain",
  "valid_assets_context",
  "tables_context",
  "column_allowlist",
  "metric_views_context",
  "tvfs_context",
  "instructions_context",
  "sample_questions_context",
  "data_profile_context",
];

const VALIDATION_PHASES = [
  { id: "1", label: "EXPLAIN — catches syntax errors and unresolvable columns" },
  { id: "2", label: "Table existence — SELECT * FROM {table} LIMIT 0 for each reference" },
  { id: "3", label: "Execution sanity — SELECT FROM (sql) LIMIT 1 verifies non-zero results" },
  { id: "4", label: "Alignment check — LLM validates question matches SQL intent" },
];

export function BenchmarksStage() {
  const factSales = FICTIONAL_EXAMPLE.tables.find((t) => t.alias === "fact_sales");
  const benchmark = FICTIONAL_EXAMPLE.benchmark;

  const visual = (
    <div className="grid gap-6 lg:grid-cols-2">
      <motion.div
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.4 }}
      >
        <Card className="overflow-hidden border border-db-gray-border">
          <CardHeader className="py-3">
            <p className="text-sm font-semibold">Schema: {factSales?.fqn ?? "fact_sales"}</p>
          </CardHeader>
          <CardContent className="pt-0">
            <div className="space-y-1.5">
              {factSales?.columns.map((col) => (
                <div
                  key={col.name}
                  className="flex justify-between gap-2 font-mono text-xs"
                >
                  <span className="text-foreground">{col.name}</span>
                  <span className="text-muted-foreground">{col.type}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </motion.div>
      <motion.div
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.4, delay: 0.15 }}
      >
        <Card className="overflow-hidden border-l-4 border-l-db-blue">
          <CardHeader className="py-3">
            <p className="text-sm font-semibold">Benchmark</p>
          </CardHeader>
          <CardContent className="pt-0 space-y-3">
            <div>
              <p className="text-xs font-medium text-muted-foreground">Question</p>
              <p className="text-sm">{benchmark.question}</p>
            </div>
            <div>
              <p className="text-xs font-medium text-muted-foreground">Expected SQL</p>
              <pre className="overflow-x-auto rounded bg-db-gray-bg p-2 text-xs">
                {benchmark.expectedSql.replace(/\\n/g, "\n")}
              </pre>
            </div>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );

  return (
    <StageScreen
      title="Generating Benchmarks"
      subtitle="Create and validate evaluation questions"
      pipelineGroup="preflight"
      visual={visual}
      explanation={
        <>
          Benchmarks are (question, expected_sql) pairs generated by an LLM using your table
          schema, data profile, and existing Genie Space configuration as context. They&apos;re
          the &quot;test suite&quot; the optimizer uses to measure improvement.
        </>
      }
      learnMore={[
        {
          id: "llm-context",
          title: "LLM Context Injection",
          content: (
            <div className="flex flex-wrap gap-2">
              {LLM_CONTEXT_BLOCKS.map((block) => (
                <Badge key={block} variant="secondary" className="font-mono text-xs">
                  {block}
                </Badge>
              ))}
            </div>
          ),
        },
        {
          id: "benchmark-model",
          title: "Benchmark Data Model",
          content: (
            <DataModelCard
              title="Benchmark Data Model"
              fields={BENCHMARK_MODEL_FIELDS}
              compact
            />
          ),
        },
        {
          id: "coverage-gap",
          title: "Coverage Gap Filling",
          content: (
            <p className="text-sm">
              <code className="rounded bg-db-gray-bg px-1.5 py-0.5">_compute_asset_coverage</code>{" "}
              identifies zero-coverage assets, generates 1–2 questions per uncovered asset, with a
              soft cap of 25.
            </p>
          ),
        },
        {
          id: "validation-pipeline",
          title: "Validation Pipeline",
          content: <AnimatedChecklist items={VALIDATION_PHASES} />,
        },
        {
          id: "train-heldout",
          title: "Train/Held-Out Split",
          content: (
            <p className="text-sm">
              Every 5th synthetic → held_out; curated shuffle with seed=42 at 80/20.
            </p>
          ),
        },
      ]}
    />
  );
}
